#!/bin/bash

# Getting
domain=$(cat /etc/xray/domain)
sldomain=$(cat /root/nsdomain)
cdndomain=$(cat /root/awscdndomain)
slkey=$(cat /etc/slowdns/server.pub)
cftn=$(cat /root/cloudfront)

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                 ⇱ CREATE ACCOUNT ⇲            "
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Login=$1
if [ -z $Login ]; then
menu-ssh
fi

Pass=$2
masaaktif=$3
max=$4

if [ "$max" -eq 1 ]; then
    echo "minimal limit ip 2"
    exit 0
fi

echo "$max" >/etc/cybervpn/limit/ssh/ip/$Login
IP=$(wget -qO- ipinfo.io/ip)
ws="$(cat ~/log-install.txt | grep -w "Websocket TLS" | cut -d: -f2 | sed 's/ //g')"
ws2="$(cat ~/log-install.txt | grep -w "Websocket None TLS" | cut -d: -f2 | sed 's/ //g')"
ssl="$(cat ~/log-install.txt | grep -w "Stunnel5" | cut -d: -f2)"
sqd="$(cat ~/log-install.txt | grep -w "Squid" | cut -d: -f2)"
ovpn="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
ovpn2="$(netstat -nlpu | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"

clear
systemctl daemon-reload
systemctl start $login
systemctl stop client-sldns
systemctl stop server-sldns
pkill sldns-server
pkill sldns-client
systemctl enable client-sldns
systemctl enable server-sldns
systemctl start client-sldns
systemctl start server-sldns
systemctl restart client-sldns
systemctl restart server-sldns
systemctl restart ws-tls
systemctl restart ws-nontls
systemctl restart ssh-ohp
systemctl restart rc-local
systemctl restart dropbear-ohp
systemctl restart openvpn-ohp

useradd -e $(date -d "$masaaktif days" +"%Y-%m-%d") -s /bin/false -M $Login
expi=$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')
echo -e "$Pass\n$Pass\n" | passwd $Login &> /dev/null
hariini=$(date -d "0 days" +"%Y-%m-%d")
expi=$(date -d "$masaaktif days" +"%Y-%m-%d")
clear

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                 ⇱ INFORMASI AKUN SSH ⇲            "
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Username: $Login"
echo "Password: $Pass"
echo "Created: $hariini"
echo "Expired: $expi"
echo "limit ip: $max"
echo "=================HOST-SSH===================="
echo "IP/Host: $IP"
echo "Domain SSH: $domain"
echo "Domain Cloudflare: $domain"
echo "PubKey : $slkey"
echo "Nameserver: $sldomain"
echo "Host Cloudfront: $cftn"
echo "===============Service-Port=================="
echo "OpenSSH: 22"
echo "Dropbear: 44, 69, 143"
echo "STunnel4: 442,222,2096"
echo "SlowDNS port: 53,5300,8080"
echo "SSH Websocket SSL/TLS: 443"
echo "SSH Websocket HTTP: 80,8080"
echo "SSH Websocket Direct & enanched: 8080,8880"
echo "OPEN VPN: 1194"
echo "BadVPN UDPGW: 7100,7200,7300"
echo "Proxy CloudFront: [ON]"
echo "Proxy Squid: [ON]"
echo "OVPN TCP: http://$IP:81/tcp.ovpn"
echo "OVPN UDP: http://$IP:81/udp.ovpn"
echo "OVPN SSL: http://$IP:81/ssl.ovpn"
echo "=================================================="
echo "SNI/Server Spoof: isi dengan bug"
echo "Payload Websocket SSL/TLS"
echo "=================================================="
echo "GET wss://bug.com/ HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf]"
echo "=================================================="
echo "Payload Websocket HTTP"
echo "=================================================="
echo "GET / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf]"
echo "=================================================="
echo "Payload enanched"
echo "=================================================="
echo "PATCH /ssh-cybervpn HTTP/1.1[crlf]Host: [host][crlf]Host: ISIBUG[crlf]Upgrade: websocket[crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf][crlf]"
echo "=================================================="
echo "     Terimakasih sudah menggunakan" 
echo "        script premium SwiftGuard Lite"
echo "=================================================="

